# Generated by Django 3.2.8 on 2022-06-27 15:21

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plpPool', '0002_auto_20220627_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitor',
            options={'verbose_name': 'Monitor', 'verbose_name_plural': 'Monitores'},
        ),
        migrations.AddField(
            model_name='user',
            name='nome',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monitor',
            name='matricula',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'Formato de matrícula inválido')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
